# Generated by Django 4.2.5 on 2023-11-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whisper', '0002_uploadedtextfile_remove_uploadedaudio_text_file'),
    ]

    operations = [
    ]
