# Generated by Django 4.2.7 on 2023-11-07 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whisper', '0003_remove_uploadedaudio_text_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedaudio',
            name='text_file',
        ),
    ]
